In [2]:
import pandas as pd

In [56]:
gt_data='green_tripdata_2025-11.parquet'

In [57]:

df= pd.read_parquet(gt_data)

In [58]:
df.head()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee
0,2,2025-11-01 00:34:48,2025-11-01 00:41:39,N,1.0,74,42,1.0,0.74,7.2,...,0.5,1.94,0.0,NaN,1.0,11.64,1.0,1.0,0.00,0.0
1,2,2025-11-01 00:18:52,2025-11-01 00:24:27,N,1.0,74,42,2.0,0.95,7.2,...,0.5,0.00,0.0,NaN,1.0,9.70,2.0,1.0,0.00,0.0
2,2,2025-11-01 01:03:14,2025-11-01 01:15:24,N,1.0,83,160,1.0,2.19,13.5,...,0.5,5.00,0.0,NaN,1.0,21.00,1.0,1.0,0.00,0.0
3,2,2025-11-01 00:10:57,2025-11-01 00:24:53,N,1.0,166,127,1.0,5.44,24.7,...,0.5,0.50,0.0,NaN,1.0,27.70,1.0,1.0,0.00,0.0
4,1,2025-11-01 00:03:48,2025-11-01 00:19:38,N,1.0,166,262,1.0,3.20,18.4,...,1.5,1.00,0.0,NaN,1.0,24.65,1.0,1.0,2.75,0.0

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 46912 entries, 0 to 46911
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   VendorID               46912 non-null  int32
 1   lpep_pickup_datetime   46912 non-null  datetime64[us]
 2   lpep_dropoff_datetime  46912 non-null  datetime64[us]
 3   store_and_fwd_flag     41343 non-null  str
 4   RatecodeID             41343 non-null  float64
 5   PULocationID           46912 non-null  int32
 6   DOLocationID           46912 non-null  int32
 7   passenger_count        41343 non-null  float64
 8   trip_distance          46912 non-null  float64
 9   fare_amount            46912 non-null  float64
 10  extra                  46912 non-null  float64
 11  mta_tax                46912 non-null  float64
 12  tip_amount             46912 non-null  float64
 13  tolls_amount           46912 non-null  float64
 14  ehail_fee              0 non-null      float64
 15  improvement_surcharge  46912 non-null  float64
 16  total_amount           46912 non-null  float64
 17  payment_type           41343 non-null  float64
 18  trip_type              41342 non-null  float64
 19  congestion_surcharge   41343 non-null  float64
 20  cbd_congestion_fee     46912 non-null  float64
dtypes: datetime64[us](2), float64(15), int32(3), str(1)
memory usage: 7.0 MB

In [59]:
#ehail_fee is NAN and has all the values as float64, and the column is not in the descrption
df = df.drop(columns=['ehail_fee'])

In [11]:
!wget https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc/taxi_zone_lookup.csv

--2026-06-05 07:59:28--  https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc/taxi_zone_lookup.csv
Resolving github.com (github.com)... 140.82.121.3
Connecting to github.com (github.com)|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://release-assets.githubusercontent.com/github-production-release-asset/513814948/5a2cc2f5-b4cd-4584-9c62-a6ea97ed0e6a?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-06-05T08%3A48%3A08Z&rscd=attachment%3B+filename%3Dtaxi_zone_lookup.csv&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-06-05T07%3A47%3A31Z&ske=2026-06-05T08%3A48%3A08Z&sks=b&skv=2018-11-09&sig=KVp4OYmsy93T7l4Qg2LHpCSFZCIKeroafdbQib4ycrs%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc4MDY0NjY2OCwibmJmIjoxNzgwNjQ2MzY4LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.r3B84eShPNBxS6ckmEnMAINpL4b4qbtAqoDl9PmPr70&response-content-disposition=attachment%3B%20filename%3Dtaxi_zone_lookup.csv&response-content-type=application%2Foctet-stream [following]
--2026-06-05 07:59:28--  https://release-assets.githubusercontent.com/github-production-release-asset/513814948/5a2cc2f5-b4cd-4584-9c62-a6ea97ed0e6a?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-06-05T08%3A48%3A08Z&rscd=attachment%3B+filename%3Dtaxi_zone_lookup.csv&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-06-05T07%3A47%3A31Z&ske=2026-06-05T08%3A48%3A08Z&sks=b&skv=2018-11-09&sig=KVp4OYmsy93T7l4Qg2LHpCSFZCIKeroafdbQib4ycrs%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc4MDY0NjY2OCwibmJmIjoxNzgwNjQ2MzY4LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.r3B84eShPNBxS6ckmEnMAINpL4b4qbtAqoDl9PmPr70&response-content-disposition=attachment%3B%20filename%3Dtaxi_zone_lookup.csv&response-content-type=application%2Foctet-stream
Resolving release-assets.githubusercontent.com (release-assets.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.109.133, ...
Connecting to release-assets.githubusercontent.com (release-assets.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 12322 (12K) [application/octet-stream]
Saving to: ‘taxi_zone_lookup.csv’

taxi_zone_lookup.cs 100%[===================>]  12.03K  --.-KB/s    in 0s

2026-06-05 07:59:28 (75.8 MB/s) - ‘taxi_zone_lookup.csv’ saved [12322/12322]

In [60]:
zone_data='taxi_zone_lookup.csv'

In [61]:
df2=pd.read_csv(zone_data)

In [62]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 265 entries, 0 to 264
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   LocationID    265 non-null    int64
 1   Borough       265 non-null    str
 2   Zone          264 non-null    str
 3   service_zone  263 non-null    str
dtypes: int64(1), str(3)
memory usage: 16.9 KB

In [63]:
df2.head()

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone

In [64]:
null_columns=df2.columns[df2.isnull().any()]
print(null_columns)

Index(['Zone', 'service_zone'], dtype='str')

In [65]:
rows_with_nulls=df2[df2.isnull().any(axis=1)]
print(rows_with_nulls)

     LocationID  Borough Zone service_zone
263         264  Unknown   NV          NaN
264         265  Unknown  NaN          NaN

In [66]:
# fill the missing zone and service_zone fields with 'Unknown'
df2['Zone'] = df2['Zone'].fillna('Unknown')
df2['service_zone'] = df2['service_zone'].fillna('Unknown')

In [67]:
# view the corrected rows
print(df2.loc[[263, 264]])

     LocationID  Borough     Zone service_zone
263         264  Unknown       NV      Unknown
264         265  Unknown  Unknown      Unknown

In [68]:
# align your data types before exporting to postgresql to keep indexes efficient
df['PULocationID'] = df['PULocationID'].astype('Int64')
df['DOLocationID'] = df['DOLocationID'].astype('Int64')

In [69]:
from sqlalchemy import create_engine
engine = create_engine('postgresql+psycopg://root:root@localhost:5432/ny_taxi')

In [70]:
print(pd.io.sql.get_schema(df, name='green_taxi_data', con=engine))

CREATE TABLE green_taxi_data (
	"VendorID" INTEGER,
	lpep_pickup_datetime TIMESTAMP WITHOUT TIME ZONE,
	lpep_dropoff_datetime TIMESTAMP WITHOUT TIME ZONE,
	store_and_fwd_flag TEXT,
	"RatecodeID" FLOAT(53),
	"PULocationID" BIGINT,
	"DOLocationID" BIGINT,
	passenger_count FLOAT(53),
	trip_distance FLOAT(53),
	fare_amount FLOAT(53),
	extra FLOAT(53),
	mta_tax FLOAT(53),
	tip_amount FLOAT(53),
	tolls_amount FLOAT(53),
	improvement_surcharge FLOAT(53),
	total_amount FLOAT(53),
	payment_type FLOAT(53),
	trip_type FLOAT(53),
	congestion_surcharge FLOAT(53),
	cbd_congestion_fee FLOAT(53)
)

In [52]:
df.head(n=0).to_sql(name='green_taxi_data', con=engine, if_exists='replace')

0

In [55]:
len(df)

46912

In [73]:
df.to_sql(name='green_taxi_data', con=engine, if_exists='append', index=False, chunksize=10000)

-5

In [74]:
df2.head(n=0).to_sql(name='taxi_zone_data', con=engine, if_exists='replace')

0

In [76]:
df2.to_sql(name='taxi_zone_data', con=engine, if_exists='append', index=False)

-1

In [77]:
!uv run jupyter nbconvert --to=script module1_HW.ipynb

[NbConvertApp] Converting notebook module1_HW.ipynb to script
[NbConvertApp] Writing 1882 bytes to module1_HW.py